services:
  no-mestre:
    build: ./mestre
    container_name: no-mestre
    ports:
      - "5000:5000"
    networks:
      - rede-cluster
    environment:
      - WORKERS=http://no-1:5000/processar,http://no-2:5000/processar,http://no-3:5000/processar,http://no-4:5000/processar,http://no-5:5000/processar
      - SLICES=10
      - MAX_RETRIES=3
    volumes:
      - ./logs_visuais:/app/logs
    depends_on:
      no-1:
        condition: service_healthy
      no-2:
        condition: service_healthy
      no-3:
        condition: service_healthy
      no-4:
        condition: service_healthy
      no-5:
        condition: service_healthy

  no-1:
    build: ./worker
    container_name: no-1
    networks:
      - rede-cluster
    environment:
      - NOME_NO=Nó 1
    volumes:
      - ./logs_visuais:/app/logs
    restart: on-failure
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  no-2:
    build: ./worker
    container_name: no-2
    networks:
      - rede-cluster
    environment:
      - NOME_NO=Nó 2
    volumes:
      - ./logs_visuais:/app/logs
    restart: on-failure
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  no-3:
    build: ./worker
    container_name: no-3
    networks:
      - rede-cluster
    environment:
      - NOME_NO=Nó 3
    volumes:
      - ./logs_visuais:/app/logs
    restart: on-failure
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  no-4:
    build: ./worker
    container_name: no-4
    networks:
      - rede-cluster
    environment:
      - NOME_NO=Nó 4
    volumes:
      - ./logs_visuais:/app/logs
    restart: on-failure
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  no-5:
    build: ./worker
    container_name: no-5
    networks:
      - rede-cluster
    environment:
      - NOME_NO=Nó 5
    volumes:
      - ./logs_visuais:/app/logs
    restart: on-failure
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  rede-cluster:
    driver: bridge